project:
  type: website
  output-dir: docs

website:
  #cookie-consent: 
  #    type: implied 
  #    style: interstitial 
  #    palette: light
  google-analytics: 
    tracking-id: "G-MW9WFPT02T"
    anonymize-ip: true
  #favicon: images/icon.png
  navbar:
    #title: 
    #logo: images/home.png
    #logo-alt: 
    background: white
    foreground: black
    right:
      - about.qmd
      - publications.qmd
      - projects.qmd
      - posts.qmd
      #- icon: github
      #  href: https://github.com/sumeromer
      #- icon: twitter
      #  href: https://twitter.com/osuemer
format:
  html:
    theme: journal
    css: styles.css
    fontsize: 0.92em
    linestretch: 1.5



