project:
  type: website
  output-dir: docs

website:
  #cookie-consent: 
  #    type: implied 
  #     style: interstitial 
  #    palette: light
  google-analytics: 
    tracking-id: "G-MW9WFPT02T"
    anonymize-ip: true
  #favicon: images/icon.png
  navbar:
    title: <span style="color:#44A1A0">Ömer Sümer </span>
    #logo: images/home.png
    #logo-alt: 
    background: white
    foreground: black
    right:
      - about.qmd
      - research/index.qmd
      - blog.qmd
      - personal-writings.qmd
      # - publications.qmd
      #- icon: github
      #  href: https://github.com/sumeromer
      #- icon: twitter
      #  href: https://twitter.com/osuemer
  page-footer:
    border: false
    left: "Published with [Quarto](https://quarto.org/) v<?quarto.version?> "
    right: "© 2023 [Ömer Sümer](/about)"

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
    css: scss/styles.css
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable
    comments:
      giscus:
        repo: sumeromer/sumeromer.github.io
        category: "Comments"
        mapping: "pathname"
        reactions-enabled: true
        loading: lazy
        input-position: "bottom"
editor: visual
filters:
  - quarto-version.lua


#format:
  #html:
  #  theme: cerulean
    #theme: 
    #    - mystyles.scss
    #mainfont: 
    #css: scss/styles.css
    #fontsize: 0.92em
    #linestretch: 2.0



