---
title: "Publications"
bibliography: references.bib
---

### Peer-reviewed journal papers

* **Ö. Sümer**, P. Goldberg, S. D'Mello, P. Gerjets, U. Trautwein and E. Kasneci, "Multimodal Engagement Analysis from Facial Videos in the Classroom," in *IEEE Transactions on Affective Computing*, doi: [10.1109/TAFFC.2021.3127692](http://doi.org/10.1109/TAFFC.2021.3127692).

* P. Goldberg, **Ö. Sümer**, K. Stürmer, W. Wagner, R. Göllner, P. Gerjets, E. Kasneci and U. Trautwein, "Attentive or not? Toward a machine learning approach to assessing students’ visible engagement in classroom instruction," in *Educational Psychology Review*, 33, pp.27-49, doi: [10.1007/s10648-019-09514-z](https://doi.org/10.1007/s10648-019-09514-z).

* **Ö. Sümer**, E. Bozkir, T. Kübler, S. Grüner, S. Utz and E. Kasneci, "FakeNewsPerception: An eye movement dataset on the perceived believability of news stories," Data in Brief, 2021, doi: [10.1016/j.dib.2021.106909](https://doi.org/10.1016/j.dib.2021.106909)  


### Peer-reviewed conference papers

* **Ö. Sümer**, F. Hellmann, A. Hustinx, T.C. Hsieh, E. André and P. Krawitz, "Few-Shot Meta Learning for Recognizing Facial Phenotypes of Genetic Disorders," accepted at *Medical Informatics Europea 2023 conference*, European Federation for Medical Informatics, 2023. [(preprint)](https://arxiv.org/abs/2210.12705).

* A. Hustinx, F. Hellmann, **Ö. Sümer**, B. Javanmardi, E. André, P. Krawitz and T.C. Hsieh, "Improving Deep Facial Phenotyping for Ultra-rare Disorder Verification Using Model Ensembles," *2023 IEEE/CVF Winter Conference on Applications of Computer Vision (WACV)*, Waikoloa, HI, USA, 2023, pp. 5007-5017, doi: [10.1109/WACV56688.2023.00499](https://doi.org/10.1109/WACV56688.2023.00499). 

* **Ö. Sümer**, P. Gerjets, U. Trautwein and E. Kasneci, "Automated Anonymisation of Visual and Audio Data in Classroom Studies," Workshop on Artificial Intelligence for Education, The Thirty-Fifth AAAI Conference on Artificial Intelligence (AAAI-21), 2021. [https://arxiv.org/abs/2001.05080](https://arxiv.org/abs/2001.05080)

* **Ö. Sümer**, P. Gerjets, U. Trautwein and E. Kasneci, "Attention Flow: End-to-End Joint Attention Estimation," *2020 IEEE Winter Conference on Applications of Computer Vision (WACV)*, Snowmass, CO, USA, 2020, pp. 3316-3325, doi: [10.1109/WACV45572.2020.9093515](https://doi.org/10.1109/WACV45572.2020.9093515).

* **Ö. Sümer**, P. Goldberg, P. Gerjets, U. Trautwein and E. Kasneci, "Teachers’ Perception in the Classroom," *Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR) Workshops*, 2018, pp. 2315-2324 [https://arxiv.org/abs/1805.08897](https://arxiv.org/abs/1805.08897)

* **Ö. Sümer**, T. Dencker and B. Ommer, "Self-Supervised Learning of Pose Embeddings from Spatiotemporal Relations in Videos," *2017 IEEE International Conference on Computer Vision (ICCV)*, Venice, Italy, 2017, pp. 4308-4317, doi: 10.1109/ICCV.2017.461.

### Under Review

* M.K. Tellamekala, Ö. Sümer, B.W. Schuller, E. André, T. Giesbrecht and M. Valstar, "Are 3D Face Shapes Expressive Enough for Recognising Continuous Emotions and Action Unit Intensities?", 2022 (Under review) [https://arxiv.org/abs/2207.01113](https://arxiv.org/abs/2207.01113)


### Preprints

* **Ö. Sümer**, C. Beyan, F. Ruth, O. Kramer, U. Trautwein and E. Kasneci, "Estimating Presentation Competence using Multimodal Nonverbal Behavioral Cues," , arXiv preprint, 2021. [https://arxiv.org/abs/2105.02636](https://arxiv.org/abs/2105.02636)